ENG-166678 - Created examples for each framework
moxiworks/mds pull request #284
Opened 2023-08-01 07:22 UTC by mitcsutt

- Updated the main docs for the `mds`, `mds-angular`, `mds-react` and `mds-vue` directories.
- Created a new `examples` package. 
  - These don't get published
  - They're individually packaged, and don't install with the other packages.

2023-08-01 07:23 UTC, mitcsutt commented on lerna.json
>    ]
This was just getting annoying. I thought it would create safety but no one should be running publish locally anyway

2023-08-02 14:07 UTC, kevinleedrum requested changes
I'm glad you took the time to do this.  I think it will could really help with adoption of the design system.  I've added some suggested commits below to fix up some bits that were pasted from the react example into the other examples.

2023-08-02 22:55 UTC, mitcsutt commented
@kevinleedrum great suggestions thanks for fixing that up for me. The vue one was silly of me, put in the effort to learn how to add variables to Vue, and didn't even change their contents

2023-08-02 22:57 UTC, kevinleedrum approved these changes

2023-08-03 22:50 UTC, merged