ENG-133039 Tab Components
moxiworks/mds pull request #5
Opened 2021-06-01 15:13 UTC by kevinleedrum

This adds `mx-tabs` and `mx-tab` components.  The parent `mx-tabs` component simply handles the fill vs. stack appearance (by switching between `grid` and `inline-grid`), as well as the indicator animation.

One thing I wasn't 100% sure on: I decided to use a `label` prop for the visible label, and an `aria-label` prop for icon-only tabs.  Alternatively, we could just have one `label` prop that always feeds into the `aria-label` attribute, but then the user would have to set another prop like `icon-only` or `hide-text` to hide the text.

https://moxiworks.atlassian.net/browse/ENG-133039

2021-06-01 17:29 UTC, iamjpg requested changes
So, in regards to `label` vs `aria-label` could we go with just passing a `label` property and if it's blank give the `icon-only` treatment? Based on that switch I feel like we could populate the `aria-label` as necessary? Just a thought but I could be under-thinking it.

Is there any mapping of these tabs to inner content containers? Maybe a `mx-tab-content`? The example below is incredibly contrived with terrible property names but it paints the picture.

```
<mx-tabs fill>
  <mx-tab :selected="activeTabA === 0" icon="ph-house" label="Home" @click="activeTabA = 0" />
  <mx-tab :selected="activeTabA === 1" icon="ph-heart" label="Favorites" badge badge-class="bg-green-600" @click="activeTabA = 1" />
  <mx-tab :selected="activeTabA === 2" icon="ph-magnifying-glass" label="Search" @click="activeTabA = 2" />
      
 <mx-tab-content tab-index="0">Home Container</mx-tab-content>
 <mx-tab-content tab-index="1">Favorites Container</mx-tab-content>
 <mx-tab-content tab-index="2">Search Container</mx-tab-content>
</mx-tabs>
```

Let me know what you think. This PR is ready to merge, IMO, but I wanted to hear your thoughts before I do that.

2021-06-01 17:29 UTC, iamjpg commented on src/components/mx-tab/mx-tab.tsx
> +      <Host class={this.tabClass} style={{ width: `${this.badge && this.label ? '133' : '120'}px` }}>
Should we move this style attribute logic into the `this.tabClass` method and return a custom class determining the width from the `mx-tabs` scss? Just a thought. I don't have a strong opinion on it either way.

2021-06-01 17:29 UTC, iamjpg commented on src/components/mx-tabs/mx-tabs.tsx
> +  animateIndicator(e: MouseEvent | KeyboardEvent) {
🔥

2021-06-01 17:41 UTC, kevinleedrum commented
>So, in regards to label vs aria-label could we go with just passing a label property and if it's blank give the icon-only treatment? Based on that switch I feel like we could populate the aria-label as necessary? Just a thought but I could be under-thinking it.

Cool, that's basically what I have now, with the hope that if someone doesn't provide `label` then they will provide `aria-label` for screen readers.  :+1:

>Is there any mapping of these tabs to inner content containers? Maybe a mx-tab-content? The example below is incredibly contrived with terrible property names but it paints the picture.

I didn't bake any view-switching into this component because I was imagining this potentially being used alongside the frontend framework's routing.  If we think someone might want to have a quick way to set up some tab views on the page that aren't really route views, then yeah, we should probably do something like what you're proposing.

2021-06-01 19:59 UTC, iamjpg commented
Awesome on the aria-label front. That seems right to me. I do think we should account for non-route based tab switching. I agree with the route based approach too - just that I can see a column widget using tabs that are local without routing...

2021-06-02 20:17 UTC, iamjpg approved these changes
🔥

2021-06-02 20:17 UTC, iamjpg commented on vuepress/css-documentation/elevations.md
> +# Elevations
lol - get me behind a keyboard and things get spelled horribly wrong. good catch.

2021-06-02 20:19 UTC, merged